### ISSUE TITLE
OAuth authentication

### ISSUE THREAD

**Issue by rcurrier666** [hay/node-disqus#4]
Anyone interested in OAuth authentication support for this package? I have working code using the OAuth NPM that I could contribute.

**Comment by dmatt** [comment]
I'm interested @rcurrier666 and I'm on the support team at Disqus :). I'm considering using this package for a small project I'm working on right now. Anything I can help with?

**Comment by hay** [comment]
@rcurrier666 would you be interested in becoming the maintainer of this package? I'm not planning on doing any more development, but if you're interested i would be happy to transfer rights of this repo to you.

**Comment by rcurrier666** [comment]
@hay, I'm willing to take over the maintenance of the package if you no long want to deal with it. There seems to be an outstanding pull request already, but not a lot of suggestions or users so I should have the time. I'll have to learn how to be a package maintainer, but it can't be that hard (and I have 40+ years of software experience under my belt so I'm really good at picking up new concepts quickly. So if you want, go ahead and transfer it to me and I'll integrate the outstanding pull request as well as add in the OAuth support.

**Comment by rcurrier666** [comment]
@dmatt, no offense but there are actually support people at Disqus? Is there any support for the API or just for integrating the service into a web site? The support@disqus email just returns an email saying it is not a support address and there doesn't seem to be any Disqus people responding on the Disqus Disqus board.

What I desperately need is a way to pass a small amount of data through the getAuthorizeUrl call back to my redirect_uri. The way it works for the other API I'm using is to simply add a query string to the end of the redirect_uri and that gets returned in the callback querystring. The Disqus API seems to require the redirect_uri to match exactly to the one on the admin page. The alternative approach some API take is to accept a "state" parameter to any endpoint that takes the redirect_uri. Normally its intended to be used as a datum to verify that the callback is actually in response to something my app did as opposed to someone attempting to DDOS my site. Plus it is a handy way to pass back small amounts of data (in my case the account ID of the user who is connecting their Disqus account to their account in my app). If this is something you can put forward to the API developers or if you can let me know the proper channel to ask for changes, I'm happy to provide more details of what I'm trying to do.

In the meantime, I hope to have simple OAuth support added to the NPM next week (at least in my branch). Full integration will likely take a bit longer as the existing code may need a bit of rework to make everything simple and transparent.

**Comment by hay** [comment]
@rcurrier666 i made a transfer request. Good luck with this project!

**Comment by dmatt** [comment]
@rcurrier666 thanks for the feedback, sorry that we haven't connected with you in the past. I'm reviewing all the details you shared and I can get in touch with you directly, and work with our engineers to help you out. Can you shoot me an email at dmatt @ disqus ? Thanks for contributing to this project.

**Comment by rcurrier666** [comment]
Version 0.3.0
